# -*- coding: utf-8 -*-
"""data_cleaning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1As3QR_e0Q7PZ2G5_Qe7dmaL8mV6fNTlu
"""

# https://towardsdatascience.com/3-ways-to-load-csv-files-into-colab-7c14fcbdcb92
from google.colab import files
uploaded = files.upload()

import io
import pandas as pd
col_list = ["comment_body"]
df = pd.read_csv(io.BytesIO(uploaded['houston_comments_Movingsubreddit.csv']), usecols=col_list)
# Dataset is now stored in a Pandas Dataframe

df.head

