# -*- coding: utf-8 -*-
"""reddit_scraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OsPg32WUHJm4yYtWhzd2q9wIXDYnZBH3
"""

!pip install -q praw
#######
# IMPORT PACKAGES
#######

import praw
import pandas as pd


# Acessing the reddit api

reddit = praw.Reddit(client_id="JhyVRsd7Ba6Vj_1ch_vLGg",      # your client id
                     client_secret="MA4GPX2deG5RTWESekP238Ji64oucQ",  #your client secret
                     user_agent="scrape", #user agent name
                     username = "",     # your reddit username
                     password = "")     # your reddit password

from google.colab import files
sub = ['nyc', 'phoenix', 'LosAngeles', 'philadelphia', 'Dallas', 'sandiego', 'sanantonio', 'SanJose', 'chicago', 'sanfrancisco']  # make a list of subreddits you want to scrape the data from

for s in sub:
    
    subreddit = reddit.subreddit(s)   # Chosing the subreddit
    from google.colab import files

# using search a keyword
    query = ['Moving']

    i = 0
    for item in query:
        post_dict = {
            "title" : [],   #title of the post
            "score" : [],   # score of the post
            "id" : [],      # unique id of the post
            "url" : [],     #url of the post
            "comms_num": [],   #the number of comments on the post
            "created" : [],  #timestamp of the post
            "body" : []         # the descriptionof post
        }
        comments_dict = {
            "comment_id" : [],      #unique comm id
            "comment_parent_id" : [],   # comment parent id
            "comment_body" : [],   # text in comment
            "comment_link_id" : []  #link to the comment
        }
        for submission in subreddit.search(query,sort = "top"): #,limit = 100):
            post_dict["title"].append(submission.title)
            post_dict["score"].append(submission.score)
            post_dict["id"].append(submission.id)
            post_dict["url"].append(submission.url)
            post_dict["comms_num"].append(submission.num_comments)
            post_dict["created"].append(submission.created)
            post_dict["body"].append(submission.selftext)
            
            ##### Acessing comments on the post
            submission.comments.replace_more() #limit = 1)
            for comment in submission.comments.list():
                comments_dict["comment_id"].append(comment.id)
                comments_dict["comment_parent_id"].append(comment.parent_id)
                comments_dict["comment_body"].append(comment.body)
                comments_dict["comment_link_id"].append(comment.link_id)
        
        post_comments = pd.DataFrame(comments_dict)
        post_comments.to_csv(s+"_comments_"+ item +"subreddit.csv")
        files.download(s+"_comments_"+ item +"subreddit.csv")

        post_data = pd.DataFrame(post_dict)
        post_data.to_csv(s+"_"+ item +"subreddit.csv")
        files.download(s+"_"+ item +"subreddit.csv")

post_comments.head

post_data.head